name: Waka Readme

on:
  schedule:
    # Runs at 12am IST
    - cron: '30 18 * * *'

jobs:
  update-readme:
    name: Update this repo's README
    runs-on: ubuntu-latest
    steps:
      - uses: anmol098/waka-readme-stats@master 
        with:
          WAKATIME_API_KEY: ${{ secrets.05248eaf-768b-4315-b3a0-23ee0aad4268 }}
          GH_TOKEN: ${{ secrets.be9fc482dc2ecf12f49a2733f6a8e89f17386ad7 }}
          SHOW_PROJECTS: "True"
          SHOW_COMMIT: "True"
          SHOW_LANGUAGE : "True"
          SHOW_TIMEZONE: "False"
          SHOW_EDITORS: "False"
          SHOW_LOC_CHART: "False"
          SHOW_LANGUAGE_PER_REPO: "True"
          SHOW_PROFILE_VIEWS: "True"
          SHOW_SHORT_INFO: "False"
